config/routes.rb
Rails.application.routes.draw do
  mount Users::Engine => "/"

  resources :accounts do
    resource :imports, only: [ :new, :create ]
    resources :movements, shallow: true, only: %i[ index show edit update destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "accounts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  has_many :imports, dependent: :destroy
  has_many :movements, dependent: :destroy

  SETTINGS_FIELDS = [ :transaction_date_column,
                      :transaction_date_format,
                      :post_date_column,
                      :post_date_format,
                      :description_column,
                      :amount_column ]

  store :import_settings, accessors: [ *SETTINGS_FIELDS ]

  validates_presence_of :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/import.rb
class Import < ApplicationRecord
  belongs_to :account

  has_many :movements

  has_one_attached :file

  validates_presence_of :file
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :account
  belongs_to :import, optional: true
  has_one :user, through: :account
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :accounts
  has_many :movements, through: :accounts
  has_many :sessions, class_name: "Users::Session", dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  def index
    @accounts = Current.user.accounts
  end

  def show
  end

  def new
    @account = Current.user.accounts.new
  end

  def edit
  end

  def create
    @account = Current.user.accounts.new(account_params)

    if @account.save
      redirect_to @account, notice: "Account was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: "Account was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy!
    redirect_to accounts_path, notice: "Account was successfully destroyed.", status: :see_other
  end

  private
    def set_account
      @account = Current.user.accounts.find(params.expect(:id))
    end

    def account_params
      params.expect(account: [ :name, *Account::SETTINGS_FIELDS ])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  include Authentication
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_account, only: [ :new, :create ]

  def new
    @import = @account.imports.new
  end

  def create
    @import = @account.imports.new(import_params)

    if @import.save
      ImportMovementsJob.perform_later @import.id

      redirect_to account_movements_path(@account), notice: "File was successfully uploaded. You'll see the movements in your account once they've been imported."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def set_account
      @account = Current.user.accounts.find(params[:account_id])
    end

    def import_params
      params.expect(import: [ :file ])
    end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: %i[ show edit update destroy ]
  before_action :set_account, only: %i[ index show new edit ]

  def index
    @movements = @account.movements
  end

  def show
  end

  def edit
  end

  def update
    if @movement.update(movement_params)
      redirect_to @movement, notice: "Movement was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @movement.destroy!
    redirect_to @movement.account, notice: "Movement was successfully destroyed.", status: :see_other
  end

  private
    def set_account
      account_id = params[:account_id]

      if account_id
        @account = Current.user.accounts.find(account_id)
      else
        @account = @movement.account
      end
    end

    def set_movement
      @movement = Current.user.movements.find(params.expect(:id))
    end

    def movement_params
      params.expect(movement: [ :verified ])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    "py-2 px-3 mb-5 font-medium rounded-lg inline-block " +

    class_names({
      "bg-green-50 text-green-500": flash_type == "notice",
      "bg-red-50 text-red-500": flash_type == "alert"
    })
  end
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= account.name %>
  </p>

  <% if action_name == "show" %>
    <% Account::SETTINGS_FIELDS.each do |field| %>
      <p class="my-5">
        <strong class="block font-medium mb-1"><%= field.to_s.humanize %>:</strong>
        <%= account.send(field) %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "contents") do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul class="list-disc ml-6">
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": account.errors[:name].none?, "border-red-400 focus:outline-red-600": account.errors[:name].any?}] %>
  </div>

  <h2 class="font-bold text-2xl">Import settings</h2>

  <% Account::SETTINGS_FIELDS.each do |field| %>
    <div class="my-5">
      <%= form.label field %>
      <%= form.text_field field, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": account.errors[:name].none?, "border-red-400 focus:outline-red-600": account.errors[:name].any?}] %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<% content_for :title, "Editing account" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing account</h1>

  <%= render "form", account: @account %>

  <%= link_to "Show this account", @account, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to accounts", accounts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/accounts/index.html.erb
<% content_for :title, "Accounts" %>

<div class="w-full">
  <div class="mb-10 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Accounts</h1>
    <%= link_to "New account", new_account_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="accounts" class="min-w-full grid grid-cols-1 gap-4 sm:grid-cols-2">
    <% if @accounts.any? %>
      <% @accounts.each do |account| %>
        <div class="relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:border-gray-400">
          <%= link_to account, class: "focus:outline-none" do %>
            <span class="absolute inset-0" aria-hidden="true"></span>
            <p class="text-sm font-medium text-gray-900"><%= account.name %></p>
            <p class="truncate text-sm text-gray-500">Amount to date</p>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No accounts found.</p>
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<% content_for :title, "New account" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New account</h1>

  <%= render "form", account: @account %>

  <%= link_to "Back to accounts", accounts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/accounts/show.html.erb
<% content_for :title, "Showing account" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing account</h1>

  <%= render "account", account: @account %>

  <%= link_to "View movements", account_movements_path(@account), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Edit this account", edit_account_path(@account), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to accounts", accounts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this account", @account, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>

app/views/common/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_classes(type) %>">
    <%= message %>
  </div>
<% end %>

app/views/common/_menu.html.erb
<nav class="mb-10 flex justify-between items-center">
  <%= link_to "Personal Finances", main_app.root_path %>

  <ul class="flex space-x-4">
    <% if authenticated? %>
      <li><%= Current.user.email_address %></li>
      <li><%= button_to "Sign out", users.session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign in", users.new_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/imports/new.html.erb
<% content_for :title, "Import movements" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Import movements to <%= @account.name %></h1>

  <%= form_with(model: @import, url: [@account, @import], class: "contents") do |form| %>
    <div class="my-5">
      <%= form.label :file %>
      <%= form.file_field :file, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": @import.errors[:name].none?, "border-red-400 focus:outline-red-600": @import.errors[:name].any?}] %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>

  <%= link_to "Back to account", accounts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Personal Finances" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto my-10 px-5">
      <%= render "common/menu" %>
      <%= render "common/flash" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/movements/_form.html.erb
<%= form_with(model: movement, class: "contents") do |form| %>
  <% if movement.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul class="list-disc ml-6">
        <% movement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 flex items-center space-x-3">
    <%= form.label :verified %>
    <%= form.checkbox :verified, class: ["shadow rounded-md border outline-none mt-2 h-5 w-5", {"border-gray-400 focus:outline-blue-600": movement.errors[:verified].none?, "border-red-400 focus:outline-red-600": movement.errors[:verified].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/movements/_movement.html.erb
<div id="<%= dom_id movement %>">
  <p class="my-5">
    <strong class="font-medium mb-1">Transaction date:</strong>
    <%= movement.transaction_date %>
  </p>
  <p class="my-5">
    <strong class="font-medium mb-1">Post date:</strong>
    <%= movement.post_date %>
  </p>
  <p class="my-5">
    <strong class="font-medium mb-1">Amount:</strong>
    <%= Money.from_cents(movement.amount, :usd).format %>
  </p>
  <p class="my-5">
    <strong class="font-medium mb-1">Verified:</strong>
    <%= movement.verified %>
  </p>
  <p class="my-5">
    <strong class="font-medium mb-1">From import:</strong>
    <%= movement.import.created_at %>
  </p>
</div>

app/views/movements/edit.html.erb
<% content_for :title, "Editing movement" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing movement</h1>

  <%= render "form", movement: @movement %>

  <%= link_to "Show this movement", @movement, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to movements", account_movements_path(@account), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/movements/index.html.erb
<% content_for :title, "Movements" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Movements</h1>
    <%= link_to "Import movements", new_account_imports_path(@account), class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="movements" class="my-10 min-w-full flow-root">
    <% if @movements.any? %>
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black/5 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Transaction date</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Post date</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Amount</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
                  <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                    <span class="sr-only">Options</span>
                  </th>
                </tr>
              </thead>

              <tbody class="divide-y divide-gray-200 bg-white">
                <% @movements.each do |movement| %>
                  <tr>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm text-gray-500 sm:pl-6"><%= movement.transaction_date %></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= movement.post_date %></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= Money.from_cents(movement.amount, :usd).format %></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= link_to movement.description, movement %></td>
                    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                      <% if !movement.verified?%>
                        <%= button_to "Verify", movement, method: :put, params: { movement: { verified: true } }, form_class: "ml-2 inline-block", class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 font-medium" %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/movements/new.html.erb
<% content_for :title, "New movement" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New movement</h1>

  <%= render "form", movement: @movement %>

  <%= link_to "Back to movements", movements_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/movements/show.html.erb
<% content_for :title, "Showing movement" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= @movement.description %></h1>

  <%= render "movement", movement: @movement %>

  <%= link_to "Edit this movement", edit_movement_path(@movement), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to movements", account_movements_path(@account), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this movement", @movement, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>